name: Build


on:
  push:
    branches:
      - 'graalvm'

jobs:
  build-java:
    name: "Build Java"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11
      - name: Build with Maven
          run: mvn -B clean install --file pom.xml
  build-linux:
    name: "Build Linux"
    runs-on: ubuntu-latest
    steps:
      - name: setup-graalvm-ce
          uses: rinx/setup-graalvm-ce@v0.0.4
          with:
            graalvm-version: "20.1.0"
            java-version: "java11"
            native-image: "true"
      - name: version
        run: |
          java -version
          native-image --version
