name: Build


on:
  push:
    branches:
      - 'graalvm'

jobs:
  build-linux:
    name: "Build Linux"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: setup-graalvm-ce
        uses: rinx/setup-graalvm-ce@v0.0.4
        with:
          graalvm-version: "20.1.0"
          java-version: "java11"
          native-image: "true"
      - name: version
        run: |
          java -version
          native-image --version
      - name: Build with Maven
        run: mvn -B clean install --file pom.xml
      - name: Build Native Image
        run: native-image --no-server -cp target/simplelocalize-cli-*.jar io.simplelocalize.cli.SimplelocalizeCliCommand
      - uses: actions/upload-artifact@v2
        with:
          name: output-linux
          path: |
            io.simplelocalize.cli.SimplelocalizeCliCommand
            target/

